### ISSUE TITLE
Samll question ?

### ISSUE THREAD

**Issue by dibarcos** [smoralis/footuner#1]
Hy, and thanks for your wonderful skin, i would like to know if it is possible to load " artist images" but i don't want to save them ...as you do with lastfm cover art ?
thanks

**Comment by smoralis** [comment]
It is impossible to display any image without first downloading it.
Lastfm cover art is saved in the user-data/lastfm_cover folder.
Artist art in the biography panel is saved in the user-data/yttm/art_img folder

**Comment by dibarcos** [comment]
ok i see, but is it possible to do like lastfm-cover for artist art ; my user-data/yttm/art_img folder is 2go in two weeks !

**Comment by smoralis** [comment]
You can limit the number of images per artist to get downloaded.
Change 
Image [Artist] Initial Fetch Number (1-20)=5
in the file
/profile/yttm/biography.ini#L76

**Comment by dibarcos** [comment]
yes , i see that, so no posibilty to save and change image when artist change ?

**Comment by smoralis** [comment]
What I suggested is only possible.
