### ISSUE TITLE
footuner on Ubuntu/Mint

### ISSUE THREAD

**Issue by tomaasz** [smoralis/footuner#2]
Hi 

Is it any way to use footuner with foobar2000 on Ubuntu/Mint ?

**Comment by smoralis** [comment]
Did you attempt it?

This thread may help.
https://hydrogenaud.io/index.php?topic=121786

In a quick test in a VM, most seem to be working.
Used latest wine 7.0 with 32prefix. 
Installed Gecko package. 
Applied DPI fix. 
sh winetricks wsh57 mdac28 gdiplus

**Comment by tomaasz** [comment]
thank you, I'm noob, so I need step-by-step guide. I've asked for this in the thread
