### ISSUE TITLE
When using presets, the currently selected playlist gets cleared/overwritten

### ISSUE THREAD

**Issue by FaceCrap** [smoralis/footuner#4]
When you click a preset, the currently active playlist is cleared/overwritten with the clicked preset.

In the quickpresets.js I see the following line in the play function

`        let cmd = "\"" + fb.FoobarPath + "foobar2000.exe" + "\"" + "/run_main:\"View/Switch to playlist/Presets Playlist\" /run_main:Edit/Clear /add /immediate " + "\"" + filename + "\"";
`

So it seems as if the intention is to switch to a playlist named "Presets", but it doesn't since the playlist in question is just named "Presets" and not "Presets Playlist"
Fix would be easy, Either change the name of the playlist or remove the " Playlist"  bit from the command. I opted for the latter since I don't need a playlist to tell me it's a playlist...

**Comment by smoralis** [comment]
fixed with
https://github.com/smoralis/footuner/commit/e78713b665c1f9a36f2ebed18bfe18c197fc3a0c
