### ISSUE TITLE
Nothing works, am I missing some steps?

### ISSUE THREAD

**Issue by ibin7777** [smoralis/footuner#5]
Here are the issues encountered under each radio station:

## 1. Tunein: Infinite building menu... 
![image](https://github.com/smoralis/footuner/assets/64576479/d05bdf5f-45d3-4511-8b40-5f4de84b3405)

## 2. Community radio browser: instant crash upon clicking the icon
![image](https://github.com/smoralis/footuner/assets/64576479/c329c201-ba64-4aaf-8a47-bd7c57934a03)
Log:
```
Error: Spider Monkey Panel v1.5.2 (Directories Search Menu: Directories Search Menu by zeremy)
ReadTextFile failed:
Path does not point to a valid file: C:\Software\Footuner\foobar2000\profile\themes\footuner\crb_countries.json

File: crb.js
Line: 35, Column: 38
Stack trace:
  crb_main_menu@crb.js:35:38
  buttonss/buttons.buttons.crb<@directories_search.js:43:13
  _button/this.lbtn_up@helpers.js:28:9
  _buttons/this.lbtn_up@helpers.js:90:27
  on_mouse_lbtn_up@directories_search.js:120:13
```

## 3. Live365 search: large porportion of the channels either has infinite awaiting responce or failes at ffprobe timeout.
![image](https://github.com/smoralis/footuner/assets/64576479/c4901ecd-566e-443d-9246-594082d09ef9)
![image](https://github.com/smoralis/footuner/assets/64576479/fce3aa9c-b833-4280-96dd-9fc153788f36)

## 4. Live 365 search(working channels) & Icecast search: channel info working fine but not playable
![image](https://github.com/smoralis/footuner/assets/64576479/ed752c1a-7883-4284-8386-296c3d849f50)
Log:
```
[16:41:44] Opening track for playback: "C:\Software\Footuner\foobar2000\user-data\mtags\LushStarr Radio - 1952220646\LushStarr Radio - 1952220646.tags" / index: 1
[16:41:44] m-TAGS:: REFERENCED FILE: http://s10.voscast.com:7434/lushstarr [0]
[16:41:44] m-TAGS:: Cannot open referenced file as media source: http://s10.voscast.com:7434/lushstarr [0]
[16:41:44] m-TAGS:: REFERENCED FILE: http://s10.voscast.com:7434/lushstarr [0]
[16:41:44] m-TAGS:: REFERENCED FILE: http://s10.voscast.com:7434/lushstarr [0]
[16:41:44] m-TAGS:: REFERENCED FILE: http://s10.voscast.com:7434/lushstarr [0]
[16:41:44] m-TAGS:: REFERENCED FILE: http://s10.voscast.com:7434/lushstarr [0]
```

**Comment by ibin7777** [comment]
environment:
windows 11 with a foobar2000 v2.0 portable install

**Comment by smoralis** [comment]
2. Fixed  https://github.com/smoralis/footuner/commit/2fc21f406529d59d9240bbcd04b352b81f98cc95

1. & 4. Without proxy do you encounter the same problems?

3. Known issue, a lot of stations are broken.

**Comment by ibin7777** [comment]
2. Tested worked fine now.

3. understood.

1 & 4: Yes, some channels that are in the cue now playable with proxy turned off, don't know why I didn't try that in the first place.

However, connection is bad and most of the channels tested keeps breaking off and on due to low connection speed.
Tunein radio still simply can't connect, that's within expectation since Tunein is not accessible without vpn in my place (as well as a lot of other sources).

So judging on the test above, I presume there's some conflict between footuner and foobar's proxy settings.
It's completely understandable if it's too much of a hassle to tackle this issue since not everyone uses proxy and is familiar with it, but if you are willing to look into it, I will keep assisting you on testing.
I'm no developer, but my place of residence has granted me the habbit of using proxy service 24/7, the least I can do is test and give feedback.

**Comment by smoralis** [comment]
Could you test  a separate **clean** foobar2000 installation with the same proxy settings  , to see if they are playable ?

Please provide console log  results.

**Comment by ibin7777** [comment]
Apologies for being a fool... Apparently foobar only supports http proxy while I typed https.
Now the existing channels can be played under http proxy.

Now logically it immediately came to my mind that **the components did not follow the proxy settings**, otherwise it won't connect at all just like the radio playback.

So here's my summary of the issue: 
1. Foobar2000, despite having an advanced settings option that claims to force http connections go through proxy settings, does not seem to handle connections that come from components (at least spider monkey panel, not sure if it's all components since others don't really need internet)
2. Not sure if there is a way for components to follow foobar proxy settings.
3. If 2nd point is not true, then it's an issue for the Foobar, if 2nd point is true, then we still need to check if it's possible to let spidermonekypanel to follow it using only custom scripts inside the panel.

So as I see it, this issue should very likely be tend to elsewhere, either spidermonkeypanel or Foobar itself requires changes. I see a very slim chance that it can somehow be done through merely panel script. Thus I'll just close this issue for now. You can reopen it if you are still interested in this matter or want to have further confirmation.
