### ISSUE TITLE
[Suggestion] Frame for volume & output device

### ISSUE THREAD

**Issue by ibin7777** [smoralis/footuner#6]
I have a need of constantly change output device and set separate volume, wonder if it's possible to have a space for that.

here's my own foobar example:
![image](https://github.com/smoralis/footuner/assets/64576479/ba6244de-737c-44d3-bd83-ee967cdcde33)
it could be anywhere in the player, just hoping for easier access than in the preference window.

**Comment by smoralis** [comment]
Volume bar is here.

![image](https://github.com/smoralis/footuner/assets/3080179/0be6612a-5e26-476d-a3e7-707216ed1f4f)

You can add the change output device in the layout by yourself . (maybe next to the volume bar ?)

![image](https://github.com/smoralis/footuner/assets/3080179/8a914c92-8f7b-4ab4-88dc-4ef4b2a3fb4e)

Don't forget to press the save button or the changes will not be saved.

![image](https://github.com/smoralis/footuner/assets/3080179/8047873f-4e30-4042-a1cc-6269d00599c2)

**Comment by ibin7777** [comment]
Very helpful, thank you.
