### ISSUE TITLE
[Suggestion] Soma FM

### ISSUE THREAD

**Issue by ibin7777** [smoralis/footuner#7]
Please consider adding Soma FM radio stations, they are the best music radio in the world!

**Comment by smoralis** [comment]
Add them with Tunein menu .
Search station.. SomaFM
Select ..

![image](https://github.com/smoralis/footuner/assets/3080179/62e12827-a9f9-41ea-9cae-1913c55b64eb)

**Comment by ibin7777** [comment]
NICE
