### ISSUE TITLE
[Suggestion] Global Dark mode including windows frame

### ISSUE THREAD

**Issue by ibin7777** [smoralis/footuner#8]
Since foobar v2 now supports a complete dark look, there might be an easy way to do that?

Here's my own foobar radio player for example:
no columns ui needed.
![image](https://github.com/smoralis/footuner/assets/64576479/36dc7e55-a3fe-4fc8-8632-592cdb4f96fb)

**Comment by smoralis** [comment]
Many required components have not been updated to support the new dark mode.
