### ISSUE TITLE
Icon/Font use

### ISSUE THREAD

**Issue by FaceCrap** [smoralis/footuner#9]
Something that has been bugging me for as long as I am using FooTuner.

For some reason it never shows the custom icons in the JS-Playlist. Like in the State column it's always switching between U and W when playing, and the Rating column always shows as 5 ê's (I don't use rating so normally hide it, but still)

**Comment by smoralis** [comment]
Install the following font in your system.
https://github.com/smoralis/footuner/blob/master/profile/themes/footuner/fontawesome-webfont.ttf

**Comment by FaceCrap** [comment]
> Install the following font in your system. https://github.com/smoralis/footuner/blob/master/profile/themes/footuner/fontawesome-webfont.ttf

My apologies, I should have mentioned the font is installed,  I'm not entirely clueless 😉

![image](https://github.com/smoralis/footuner/assets/95778718/3ba98a71-35b5-42d7-9803-516527c78249)

Yet, I still don't get to see the icons where they should show.

**Comment by smoralis** [comment]
ok, could you also install Guifx v2 Transports font?

https://www.dafont.com/guifx-v2-transports.font

**Comment by FaceCrap** [comment]
Ok, so that fixed the rating stars... something I never use... but the playing indicator still toggles between w and u
![image](https://github.com/smoralis/footuner/assets/95778718/42668735-ed24-4663-8ede-0604e4810e66)

**Comment by smoralis** [comment]
check if the wingdings fonts are installed
https://github.com/smoralis/footuner/blob/042f1cb4cc2aef6c0f35edac570866f38186bb3e/profile/themes/footuner/js/samples/jsplaylist-mod/js/main.js#L2502

profile/themes/footuner/js/samples/readme.md

**Comment by FaceCrap** [comment]
wingdings and webdings  are both installed

**Comment by smoralis** [comment]
Problem noted.👍
I will add the information to the main readme.
